name: Build with NodeJS and Grunt

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: "Install dependencies and build artifact"
      run: |
        npm install -g grunt-cli
        npm install -g bower
        npm install
        bower install
        grunt

    - name: "Upload artifacts"
      uses: actions/upload-artifact@v4
      with:
        name: distribution
        path: |
          dist/*
